# Generated by Django 4.0.5 on 2022-06-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayTimes', '0002_rename_praymodel_pray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pray',
            name='yo',
            field=models.ImageField(upload_to='pray_times'),
        ),
    ]
