# Generated by Django 4.0.5 on 2022-06-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayTimes', '0003_alter_pray_yo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pray',
            old_name='yo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='pray',
            name='monthNum',
            field=models.IntegerField(default=0),
        ),
    ]
