# Generated by Django 4.0.5 on 2022-06-11 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayTimes', '0004_rename_yo_pray_image_pray_monthnum'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pray',
            new_name='PrayTimeTable',
        ),
    ]
